apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capstn24-tls
  namespace: sock-shop
spec:
  secretName: capstn24-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: nayokians.me
  dnsNames:
    - nayokians.me

