---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: sock-shop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  #Acme server url
    email: engr.nnamdiemmanuel@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod        #Name of secret used to store the ACME account private key
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx     
