name: Clean Up Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destroy Terraform Infrastructure
        run: |
          terraform -chdir=terraform/ init
          terraform -chdir=terraform/ destroy --auto-approve

      - name: Delete S3 Bucket
        run: |
          aws s3 rb s3://sock-bucket --force

      - name: Delete DynamoDB Table
        run: |
          aws dynamodb delete-table --table-name terraform-lock

      - name: Uninstall Helm Releases
        run: |
          helm uninstall capstoneapp --namespace sock-shop
          helm uninstall cert-manager --namespace sock-shop
          helm uninstall prometheus --namespace sock-shop
          helm uninstall ingress-nginx --namespace sock-shop

      - name: Delete Kubernetes Resources
        run: |
          kubectl delete -f ingress.yml --ignore-not-found
          kubectl delete -f cluster-Issuer.yml --ignore-not-found
          kubectl delete -f certificate.yaml --ignore-not-found
          kubectl delete namespace sock-shop --ignore-not-found
          kubectl delete -f aws-auth.yaml --ignore-not-found

      - name: Delete EKS Cluster
        run: |
          eksctl delete cluster --name socks-shop-CICD001 --region ${{ vars.REGION }}
